package hearth.kindlings.reactivemongobsonderivation

import reactivemongo.api.bson.BSONDocumentReader

trait KindlingsBsonDocumentReader[A] extends BSONDocumentReader[A]
object KindlingsBsonDocumentReader extends KindlingsBsonDocumentReaderCompanionCompat
