package hearth.kindlings.reactivemongobsonderivation

import reactivemongo.api.bson.BSONDocumentWriter

trait KindlingsBsonDocumentWriter[A] extends BSONDocumentWriter[A]
object KindlingsBsonDocumentWriter extends KindlingsBsonDocumentWriterCompanionCompat
